Eugenia Changes
apache-superset/docs pull request #23
Opened 2020-09-04 12:38 UTC by eugeniamz

2020-09-04 14:55 UTC, srinify requested changes

2020-09-04 14:55 UTC, srinify commented on src/pages/docs/Connecting to Databases/mysql.mdx
> +-For Localhost or docker running Linux: localhost or 127.0.0.1
Nitpicky, can we add a space after `-`

2020-09-04 14:55 UTC, srinify commented on src/pages/docs/Connecting to Databases/sql-server.mdx
> +## Sql Server
I think sql has to be all caps, this is more a trademark thing? 

"SQL Server" - https://www.microsoft.com/en-us/sql-server/sql-server-2019

2020-09-04 15:03 UTC, srinify approved these changes

2020-09-09 19:52 UTC, mistercrunch commented
that was merged into https://github.com/apache/incubator-superset/pull/10784

2020-09-09 19:52 UTC, closed without merging